const postConstants = {
  NEW: 'POST_NEW',

  CREATE_REQUEST: 'POST_CREATE_REQUEST',
  CREATE_SUCCESS: 'POST_CREATE_SUCCESS',
  CREATE_FAILURE: 'POST_CREATE_FAILURE',

  UPDATE_REQUEST: 'POST_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'POST_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'POST_UPDATE_FAILURE',

  DELETE_REQUEST: 'POST_DELETE_REQUEST',
  DELETE_SUCCESS: 'POST_DELETE_SUCCESS',
  DELETE_FAILURE: 'POST_DELETE_FAILURE',

  LIST_REQUEST: 'POST_LIST_REQUEST',
  LIST_SUCCESS: 'POST_LIST_SUCCESS',
  LIST_FAILURE: 'POST_LIST_FAILURE',

  SHOW_REQUEST: 'POST_SHOW_REQUEST',
  SHOW_SUCCESS: 'POST_SHOW_SUCCESS',
  SHOW_FAILURE: 'POST_SHOW_FAILURE',
};
export default postConstants;
